{% set name = "whitebox" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69571640a778253e27a05c63b08aed670457803798a0b8f233761eabcd39188b

build:
  number: 0
  entry_points:
    - whitebox=whitebox.cli:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - click >=6.0
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - click >=6.0
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - os

about:
  home: https://github.com/giswqs/whitebox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An advanced geospatial data analysis platform
  doc_url: https://whitebox.readthedocs.io
  dev_url: https://github.com/giswqs/whitebox

extra:
  recipe-maintainers:
    - giswqs
